# Generated by Django 3.2.8 on 2021-10-30 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='device_hub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.PositiveIntegerField(unique=True)),
                ('light_01', models.CharField(default='OFF', max_length=3)),
                ('light_02', models.CharField(default='OFF', max_length=3)),
                ('light_03', models.CharField(default='OFF', max_length=3)),
                ('last_gesture', models.CharField(default='gesture_00', max_length=10)),
            ],
        ),
    ]
